
import { User } from '../types';
import { INITIAL_BALANCE } from '../constants';
import { createClient, SupabaseClient } from '@supabase/supabase-js';

/* 
  === SUPABASE SETUP INSTRUCTIONS ===
  If you are seeing 404 errors, your database table does not exist.
  Run this SQL in your Supabase SQL Editor:

  create table users (
    id bigint generated by default as identity primary key,
    wallet_address text not null unique,
    balance numeric default 1000,
    avatar_url text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
  );
*/

export interface DatabaseProvider {
  getUser(walletAddress: string): Promise<User>;
  updateUserBalance(walletAddress: string, newBalance: number): Promise<User>;
}

// --- LOCAL SIMULATION ADAPTER (Reliable Fallback) ---
class LocalAdapter implements DatabaseProvider {
  async getUser(walletAddress: string): Promise<User> {
    const key = `pump_casino_user_${walletAddress}`;
    let stored = null;
    try {
      stored = localStorage.getItem(key);
    } catch (e) { /* ignore */ }

    if (stored) {
      return JSON.parse(stored);
    }

    // Generate a new user if one doesn't exist locally
    const newUser: User = {
      username: walletAddress,
      balance: INITIAL_BALANCE,
      avatarUrl: `https://api.dicebear.com/9.x/bottts-neutral/svg?seed=${walletAddress}`
    };
    
    try {
        localStorage.setItem(key, JSON.stringify(newUser));
    } catch (e) {}
    
    return newUser;
  }

  async updateUserBalance(walletAddress: string, newBalance: number): Promise<User> {
    const key = `pump_casino_user_${walletAddress}`;
    const currentUser = await this.getUser(walletAddress);
    const user: User = {
      ...currentUser,
      balance: newBalance
    };
    try {
        localStorage.setItem(key, JSON.stringify(user));
    } catch (e) {}
    return user;
  }
}

// --- SUPABASE ADAPTER ---
class SupabaseAdapter implements DatabaseProvider {
  private supabase: SupabaseClient;
  private localBackup: LocalAdapter;

  constructor(url: string, key: string) {
    this.supabase = createClient(url, key, {
        auth: { persistSession: false }
    });
    this.localBackup = new LocalAdapter();
  }

  async getUser(walletAddress: string): Promise<User> {
    try {
      // Attempt to fetch from real DB
      const { data, error } = await this.supabase
        .from('users')
        .select('*')
        .eq('wallet_address', walletAddress)
        .maybeSingle();

      if (error) throw error;

      if (data) {
        // Sync local backup
        this.localBackup.updateUserBalance(walletAddress, Number(data.balance));
        return { 
            username: data.wallet_address, 
            balance: Number(data.balance),
            avatarUrl: data.avatar_url || `https://api.dicebear.com/9.x/bottts-neutral/svg?seed=${walletAddress}`
        };
      }
      
      // User not found in DB, create new one
      const defaultAvatar = `https://api.dicebear.com/9.x/bottts-neutral/svg?seed=${walletAddress}`;
      const { data: newUser, error: createError } = await this.supabase
        .from('users')
        .insert([{ 
            wallet_address: walletAddress, 
            balance: INITIAL_BALANCE,
            avatar_url: defaultAvatar
        }])
        .select()
        .single();
        
      if (createError) throw createError;

      return { 
          username: newUser.wallet_address, 
          balance: Number(newUser.balance),
          avatarUrl: newUser.avatar_url
      };

    } catch (err: any) {
      // LOG THE SQL FIX TO CONSOLE SO USER SEES IT
      if (err.code === '42P01' || (err.message && err.message.includes('404'))) {
          console.group("🚨 DATABASE TABLE MISSING");
          console.log("%cPASTE THIS INTO SUPABASE SQL EDITOR:", "color: #10b981; font-size: 12px; font-weight: bold;");
          console.log(`
create table users (
  id bigint generated by default as identity primary key,
  wallet_address text not null unique,
  balance numeric default 1000,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
          `);
          console.groupEnd();
      }

      // Switch to offline mode silently to keep app working
      return this.localBackup.getUser(walletAddress);
    }
  }

  async updateUserBalance(walletAddress: string, newBalance: number): Promise<User> {
    // Optimistic update (Local first for speed)
    const localResult = await this.localBackup.updateUserBalance(walletAddress, newBalance);

    // Background sync to Supabase
    this.supabase
      .from('users')
      .update({ balance: newBalance })
      .eq('wallet_address', walletAddress)
      .then(({ error }) => {
         if (error) console.warn("Background sync failed (using local data)");
      });

    return localResult;
  }
}

// --- INIT LOGIC ---
const FALLBACK_URL = "https://wkblzroluuljlsklxyeb.supabase.co";
const FALLBACK_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrYmx6cm9sdXVsamxza2x4eWViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1ODYxMzgsImV4cCI6MjA3OTE2MjEzOH0.HpPtkq8gGZGH0-WDMyoFMuTEZwU64j397NJNLBmld1A";

const envUrl = process.env.VITE_SUPABASE_URL;
const envKey = process.env.VITE_SUPABASE_ANON_KEY;

// Prefer env vars, fallback to hardcoded
const finalUrl = (envUrl && envUrl.length > 5) ? envUrl : FALLBACK_URL;
const finalKey = (envKey && envKey.length > 5) ? envKey : FALLBACK_KEY;

export let db: DatabaseProvider;
export let isLive = false;

try {
    if (finalUrl && finalKey) {
        db = new SupabaseAdapter(finalUrl, finalKey);
        isLive = true;
    } else {
        db = new LocalAdapter();
        isLive = false;
    }
} catch (e) {
    console.error("Database init failed, falling back to local");
    db = new LocalAdapter();
    isLive = false;
}
